language: node_js
node_js:
- "12.18"
script:
  - npm install
  - npm install -g serverless
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sls deploy -v --force --conceal; fi'
branches:
  only:
    - master
