service: hyperbudget-queue-email

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-2
  stage: ${opt:stage, 'dev'}
  apiKeys:
    hbQueKey-${opt:stage}
  environment:
    DYNAMODB_TABLE: hyperbudget-email-service-${self:provider.stage}
    SQS_QUEUE: hyperbudget-email-service-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
    - Effect: Allow
      Action:
        - "sqs:SendMessage"
        - "sqs:GetQueueUrl"
      Resource: "arn:aws:sqs:${opt:region, self:provider.region}:*:${self:provider.environment.SQS_QUEUE}"
    - Effect: Allow
      Action:
        - "sqs:ListQueues"
      Resource: "arn:aws:sqs:${opt:region, self:provider.region}:*:*"

functions:
  hello:
    handler: handler.addToQueue
    environment:
      SQS_QUEUE_URL: 'https://sqs.${self:provider.region}.amazonaws.com/504193536768/hyperbudget-email-service-${self:provider.stage}'
      AWS_REGION: '${self:provider.region}'
    events:
      - http:
          path: email/send
          method: post

resources:
  Resources:
    sqsQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "${self:provider.environment.SQS_QUEUE}"
    UserEmailDBTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "Id"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "Id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
